[package]
name = "scroller"
version = "0.1.0"
authors = ["Daniel Perez Alvarez <danielpza@protonmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["image"]
